# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: '1.5.1'

    - name: Install Poetry Dynamic Versioning Plugin
      run: pip install poetry-dynamic-versioning

    - name: Install dependencies
      run: poetry install
        
    - name: Build and publish
      run: |
        poetry-dynamic-versioning
        poetry build
        poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
